name: Test GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Test Action
        run: |
          echo "GitHub Actions is working!"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          ls -la
